import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'aafful' at '1/9/15 12:13 AM' with Gradle 2.1
 *
 * @author aafful, @date 1/9/15 12:13 AM
 */
public class PrefixExpressionsTest {
    @Test public void testSomeLibraryMethod() {
        PrefixExpressions classUnderTest = new PrefixExpressions();
            }
}
